version: '3.8'

services:
  algorithm-service:
    container_name: algorithm-container
    build:
      context: ./algorithm
    ports:
      - "8000:8000"
    networks:
      - my-network
  notification-service:
    container_name: notification-container
    build:
      context: ./notification
    ports:
      - "9000:9000"
    networks:
      - my-network

networks:
  my-network: